#!/bin/bash

if [ -z "$CPM_CONFIG" ]; then
	CPM_CONFIG=~/.cpm.conf
fi

if [ -f "$CPM_CONFIG" ]; then
	source "$CPM_CONFIG"
fi

if [ -z "$CPM_PATH" ]; then
	# Set the path to your CPM directory here:
	CPM_PATH=$(cd "$(dirname "$0")"; pwd)
fi

if [ -z "$CPM_REGISTRY" ]; then
	# You can point to an alternate registry if desired:
	CPM_REGISTRY=http://packages.dojofoundation.org/
fi

export CPM_PATH
export CPM_REGISTRY

if [ -n "$CPM_USE_NODE" ]; then
	# You can use node instead of rhino, by putting "CPM_USE_NODE=1" in ~/.cpm.conf
	node "$CPM_PATH/lib/cpm.js" $@
else
	# by default we use rhino (since the JVM is installed almost everywhere)
	java -classpath "$CPM_PATH/jars/js.jar" org.mozilla.javascript.tools.shell.Main -opt -1 "$CPM_PATH/lib/cpm.js" $@
fi
